# Precision Agriculture Decision Support System

## Data Understanding

### Objective
The objective of this notebook is to understand the dataset before performing data preprocessing and feature engineering.

Tasks:
- Load Dataset
- Explore Dataset
- Check Missing Values
- Check Duplicates
- Understand Features
- Identify Target Variable

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [4]:
df = pd.read_csv("../data/raw/Crop_recommendation.csv")
df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
df.shape

(2200, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
N,2200.0,50.551818,36.917334,0.000000,21.000000,37.000000,84.250000,140.000000
P,2200.0,53.362727,32.985883,5.000000,28.000000,51.000000,68.000000,145.000000
K,2200.0,48.149091,50.647931,5.000000,20.000000,32.000000,49.000000,205.000000
temperature,2200.0,25.616244,5.063749,8.825675,22.769375,25.598693,28.561654,43.675493
humidity,2200.0,71.481779,22.263812,14.258040,60.261953,80.473146,89.948771,99.981876
ph,2200.0,6.469480,0.773938,3.504752,5.971693,6.425045,6.923643,9.935091
rainfall,2200.0,103.463655,54.958389,20.211267,64.551686,94.867624,124.267508,298.560117

In [8]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')

In [11]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [12]:
df["label"].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [13]:
df.shape
df.info()
df.isnull().sum()
df.duplicated().sum()
df.describe().T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

,count,mean,std,min,25%,50%,75%,max
N,2200.0,50.551818,36.917334,0.000000,21.000000,37.000000,84.250000,140.000000
P,2200.0,53.362727,32.985883,5.000000,28.000000,51.000000,68.000000,145.000000
K,2200.0,48.149091,50.647931,5.000000,20.000000,32.000000,49.000000,205.000000
temperature,2200.0,25.616244,5.063749,8.825675,22.769375,25.598693,28.561654,43.675493
humidity,2200.0,71.481779,22.263812,14.258040,60.261953,80.473146,89.948771,99.981876
ph,2200.0,6.469480,0.773938,3.504752,5.971693,6.425045,6.923643,9.935091
rainfall,2200.0,103.463655,54.958389,20.211267,64.551686,94.867624,124.267508,298.560117

In [24]:
crop_df = pd.read_csv("../data/raw/Crop_recommendation.csv")

district_df = pd.read_csv("../data/raw/distric_crop_data.csv")

fertilizer_df = pd.read_csv("../data/raw/fertilizer_data.csv")

faostat_2025_df = pd.read_csv("../data/raw/foastat 2025.csv")

faostat_2026_df = pd.read_csv("../data/raw/foastat 2026.csv")

weather_df = pd.read_csv("../data/raw/weather_data.csv")

In [25]:
print("Crop Recommendation:", crop_df.shape)

print("District Crop:", district_df.shape)

print("Fertilizer:", fertilizer_df.shape)

print("FAOSTAT 2025:", faostat_2025_df.shape)

print("FAOSTAT 2026:", faostat_2026_df.shape)

print("Weather:", weather_df.shape)

Crop Recommendation: (2200, 8)
District Crop: (2200, 9)
Fertilizer: (99, 9)
FAOSTAT 2025: (1115, 15)
FAOSTAT 2026: (831, 15)
Weather: (1274, 17)

In [26]:
print(crop_df.columns)

print(district_df.columns)

print(fertilizer_df.columns)

print(faostat_2025_df.columns)

print(faostat_2026_df.columns)

print(weather_df.columns)

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='object')
Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label',
       'district'],
      dtype='object')
Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')
Index(['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code',
       'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description', 'Note'],
      dtype='object')
Index(['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code',
       'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit',
       'Value', 'Flag', 'Flag Description', 'Note'],
      dtype='object')
Index(['PARAMETER', 'YEAR', 'LAT', 'LON', 'JAN', 'FEB', 'MAR', 'APR', 'MAY',
       'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANN'],
      dtype='object')

In [28]:
crop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [29]:
district_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
 8   district     2200 non-null   object
dtypes: float64(4), int64(3), object(2)
memory usage: 154.8+ KB

In [30]:
fertilizer_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temparature      99 non-null     int64
 1   Humidity         99 non-null     int64
 2   Moisture         99 non-null     int64
 3   Soil Type        99 non-null     object
 4   Crop Type        99 non-null     object
 5   Nitrogen         99 non-null     int64
 6   Potassium        99 non-null     int64
 7   Phosphorous      99 non-null     int64
 8   Fertilizer Name  99 non-null     object
dtypes: int64(6), object(3)
memory usage: 7.1+ KB

In [31]:
faostat_2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       1115 non-null   object
 1   Domain            1115 non-null   object
 2   Area Code (M49)   1115 non-null   int64
 3   Area              1115 non-null   object
 4   Element Code      1115 non-null   int64
 5   Element           1115 non-null   object
 6   Item Code (CPC)   1115 non-null   float64
 7   Item              1115 non-null   object
 8   Year Code         1115 non-null   int64
 9   Year              1115 non-null   int64
 10  Unit              1115 non-null   object
 11  Value             1115 non-null   float64
 12  Flag              1115 non-null   object
 13  Flag Description  1115 non-null   object
 14  Note              0 non-null      float64
dtypes: float64(3), int64(4), object(8)
memory usage: 130.8+ KB

In [32]:
faostat_2025_df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,586,Pakistan,5412,Yield,112.0,Maize (corn),1961,1961,kg/ha,1030.9,A,Official figure,NaN
1,QCL,Crops and livestock products,586,Pakistan,5510,Production,112.0,Maize (corn),1961,1961,t,487680.0,A,Official figure,NaN
2,QCL,Crops and livestock products,586,Pakistan,5412,Yield,112.0,Maize (corn),1962,1962,kg/ha,1052.5,A,Official figure,NaN
3,QCL,Crops and livestock products,586,Pakistan,5510,Production,112.0,Maize (corn),1962,1962,t,482600.0,A,Official figure,NaN
4,QCL,Crops and livestock products,586,Pakistan,5412,Yield,112.0,Maize (corn),1963,1963,kg/ha,1052.2,A,Official figure,NaN

In [33]:
faostat_2026_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 831 entries, 0 to 830
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       831 non-null    object
 1   Domain            831 non-null    object
 2   Area Code (M49)   831 non-null    int64
 3   Area              831 non-null    object
 4   Element Code      831 non-null    int64
 5   Element           831 non-null    object
 6   Item Code (CPC)   831 non-null    float64
 7   Item              831 non-null    object
 8   Year Code         831 non-null    int64
 9   Year              831 non-null    int64
 10  Unit              831 non-null    object
 11  Value             831 non-null    float64
 12  Flag              831 non-null    object
 13  Flag Description  831 non-null    object
 14  Note              2 non-null      object
dtypes: float64(2), int64(4), object(9)
memory usage: 97.5+ KB

In [34]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  1274 non-null   object
 1   YEAR       1274 non-null   int64
 2   LAT        1274 non-null   float64
 3   LON        1274 non-null   float64
 4   JAN        1274 non-null   float64
 5   FEB        1274 non-null   float64
 6   MAR        1274 non-null   float64
 7   APR        1274 non-null   float64
 8   MAY        1274 non-null   float64
 9   JUN        1274 non-null   float64
 10  JUL        1274 non-null   float64
 11  AUG        1274 non-null   float64
 12  SEP        1274 non-null   float64
 13  OCT        1274 non-null   float64
 14  NOV        1274 non-null   float64
 15  DEC        1274 non-null   float64
 16  ANN        1274 non-null   float64
dtypes: float64(15), int64(1), object(1)
memory usage: 169.3+ KB

In [35]:
datasets = {
    "Crop Recommendation": crop_df,
    "District Crop": district_df,
    "Fertilizer": fertilizer_df,
    "FAOSTAT 2025": faostat_2025_df,
    "FAOSTAT 2026": faostat_2026_df,
    "Weather": weather_df
}

for name, df in datasets.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print(df.columns.tolist())
    print()

======================================================================
Crop Recommendation
======================================================================
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label']

======================================================================
District Crop
======================================================================
['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label', 'district']

======================================================================
Fertilizer
======================================================================
['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type', 'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name']

======================================================================
FAOSTAT 2025
======================================================================
['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code', 'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag', 'Flag Description', 'Note']

======================================================================
FAOSTAT 2026
======================================================================
['Domain Code', 'Domain', 'Area Code (M49)', 'Area', 'Element Code', 'Element', 'Item Code (CPC)', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag', 'Flag Description', 'Note']

======================================================================
Weather
======================================================================
['PARAMETER', 'YEAR', 'LAT', 'LON', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANN']

In [36]:
weather_df["PARAMETER"].unique()

array(['PRECTOTCORR_SUM'], dtype=object)

In [37]:
faostat_2025_df["Area"].unique()[:20]

array(['Pakistan'], dtype=object)

In [38]:
faostat_2025_df["Item"].unique()[:20]

array(['Maize (corn)', 'Other pulses n.e.c.', 'Potatoes', 'Rice',
       'Seed cotton, unginned', 'Sorghum', 'Sunflower seed', 'Tomatoes',
       'Wheat'], dtype=object)

In [2]:
import pandas as pd
temp_df = pd.read_csv("../data/raw/Temperature_data.csv", skiprows=9)

hum_df = pd.read_csv("../data/raw/Humidity_data.csv", skiprows=9)

rain_df = pd.read_csv("../data/raw/Rainfall_data.csv", skiprows=9)

In [4]:
temp_df

,PARAMETER,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,T2M,2000,28.0,65.625,9.74,10.49,15.54,24.53,30.17,29.49,30.16,29.53,26.59,21.03,14.27,11.28,21.10
1,T2M,2000,28.0,66.250,8.38,8.88,13.95,22.76,28.61,27.87,28.93,27.93,25.10,19.90,13.27,10.47,19.70
2,T2M,2000,28.0,66.875,10.81,11.26,16.57,25.64,31.03,30.80,30.86,30.11,27.18,22.75,15.88,13.07,22.19
3,T2M,2000,28.0,67.500,16.17,16.81,22.93,32.71,37.56,37.64,37.18,36.70,33.40,29.17,21.79,18.37,28.40
4,T2M,2000,28.0,68.125,16.90,17.72,24.13,33.92,38.82,39.15,38.62,38.37,34.71,30.43,23.02,18.72,29.57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,T2M,2025,29.5,68.125,14.88,18.03,23.54,32.40,35.72,37.46,35.05,34.06,32.53,27.52,19.75,17.29,27.39
932,T2M,2025,29.5,68.750,11.93,14.68,20.15,28.78,32.31,33.93,31.36,30.29,29.45,24.36,16.97,14.72,24.12
933,T2M,2025,29.5,69.375,12.03,14.74,20.19,28.89,31.79,33.60,30.98,30.07,29.07,24.20,16.79,14.66,23.96
934,T2M,2025,29.5,70.000,14.56,17.44,22.93,31.67,34.51,36.28,33.20,33.17,31.30,26.28,19.20,16.86,26.49
935,T2M,2025,29.5,70.625,16.12,19.40,24.86,33.72,37.33,38.96,36.02,36.10,33.52,28.21,20.88,18.12,28.64

In [5]:
temp_df.shape

(936, 17)

In [6]:
temp_df.isnull().sum()

PARAMETER    0
YEAR         0
LAT          0
LON          0
JAN          0
FEB          0
MAR          0
APR          0
MAY          0
JUN          0
JUL          0
AUG          0
SEP          0
OCT          0
NOV          0
DEC          0
ANN          0
dtype: int64

In [8]:
temp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  936 non-null    object
 1   YEAR       936 non-null    int64
 2   LAT        936 non-null    float64
 3   LON        936 non-null    float64
 4   JAN        936 non-null    float64
 5   FEB        936 non-null    float64
 6   MAR        936 non-null    float64
 7   APR        936 non-null    float64
 8   MAY        936 non-null    float64
 9   JUN        936 non-null    float64
 10  JUL        936 non-null    float64
 11  AUG        936 non-null    float64
 12  SEP        936 non-null    float64
 13  OCT        936 non-null    float64
 14  NOV        936 non-null    float64
 15  DEC        936 non-null    float64
 16  ANN        936 non-null    float64
dtypes: float64(15), int64(1), object(1)
memory usage: 124.4+ KB

In [10]:
temp_df.describe()

,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
count,936.00000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.00000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000
mean,2012.50000,28.750000,68.125000,12.009455,15.217372,20.877147,27.091186,32.178333,34.446603,34.06766,32.353355,29.950171,25.165043,18.989818,13.894049,24.724829
std,7.50401,0.559316,1.614606,3.852567,4.430184,4.863842,5.023248,4.960195,4.313962,3.93114,4.000433,4.289940,4.504709,4.164874,3.854495,4.144855
min,2000.00000,28.000000,65.625000,1.100000,3.370000,8.990000,14.160000,19.680000,24.170000,23.67000,21.270000,19.460000,13.600000,8.480000,4.580000,15.020000
25%,2006.00000,28.375000,66.875000,9.100000,11.880000,17.035000,23.282500,28.157500,31.167500,31.13750,29.410000,26.497500,21.517500,15.557500,10.750000,21.467500
50%,2012.50000,28.750000,68.125000,13.285000,16.210000,22.125000,28.430000,33.710000,36.010000,35.11500,33.310000,31.070000,26.555000,20.470000,15.305000,26.365000
75%,2019.00000,29.125000,69.375000,15.120000,18.762500,24.822500,31.140000,36.422500,38.085000,37.38000,35.800000,33.640000,29.012500,22.390000,16.852500,28.320000
max,2025.00000,29.500000,70.625000,17.890000,23.670000,29.300000,35.060000,39.340000,40.460000,40.57000,38.450000,37.110000,31.510000,25.900000,21.320000,30.000000

In [11]:
hum_df

,PARAMETER,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,RH2M,2000,28.0,65.625,34.23,28.52,20.81,16.65,16.55,14.36,18.47,23.87,16.64,15.87,25.64,39.46,22.60
1,RH2M,2000,28.0,66.250,34.24,28.75,19.99,16.02,16.01,15.03,23.67,26.97,20.04,16.02,25.30,36.68,23.24
2,RH2M,2000,28.0,66.875,29.51,24.81,16.20,13.09,15.42,13.64,28.75,27.93,22.58,13.73,20.99,30.33,21.44
3,RH2M,2000,28.0,67.500,23.05,19.91,11.65,9.24,15.45,12.85,27.81,26.62,21.76,10.53,15.39,22.48,18.09
4,RH2M,2000,28.0,68.125,23.87,21.28,11.60,9.79,22.27,18.42,32.13,31.04,27.91,10.55,15.04,21.42,20.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,RH2M,2025,29.5,68.125,26.11,30.95,21.25,11.68,17.44,23.02,49.83,47.69,39.31,23.93,9.61,21.74,26.91
932,RH2M,2025,29.5,68.750,28.68,35.93,24.34,14.00,21.11,27.11,57.10,55.97,43.86,29.44,11.24,24.78,31.17
933,RH2M,2025,29.5,69.375,28.45,37.00,24.54,14.40,24.68,28.80,58.12,56.83,46.78,31.30,12.36,24.37,32.34
934,RH2M,2025,29.5,70.000,25.50,34.34,22.94,13.86,24.53,28.03,56.35,49.23,46.28,32.38,13.08,22.25,30.76
935,RH2M,2025,29.5,70.625,26.23,33.67,24.13,15.17,23.76,27.96,51.91,44.16,45.99,36.33,16.62,23.61,30.82

In [14]:
hum_df.value_counts()

PARAMETER  YEAR  LAT   LON     JAN    FEB    MAR    APR    MAY    JUN    JUL    AUG    SEP    OCT    NOV    DEC    ANN
RH2M       2000  28.0  65.625  34.23  28.52  20.81  16.65  16.55  14.36  18.47  23.87  16.64  15.87  25.64  39.46  22.60    1
                       66.250  34.24  28.75  19.99  16.02  16.01  15.03  23.67  26.97  20.04  16.02  25.30  36.68  23.24    1
                       66.875  29.51  24.81  16.20  13.09  15.42  13.64  28.75  27.93  22.58  13.73  20.99  30.33  21.44    1
                       67.500  23.05  19.91  11.65  9.24   15.45  12.85  27.81  26.62  21.76  10.53  15.39  22.48  18.09    1
                       68.125  23.87  21.28  11.60  9.79   22.27  18.42  32.13  31.04  27.91  10.55  15.04  21.42  20.47    1
                                                                                                                           ..
           2025  29.5  68.125  26.11  30.95  21.25  11.68  17.44  23.02  49.83  47.69  39.31  23.93  9.61   21.74  26.91    1
                       68.750  28.68  35.93  24.34  14.00  21.11  27.11  57.10  55.97  43.86  29.44  11.24  24.78  31.17    1
                       69.375  28.45  37.00  24.54  14.40  24.68  28.80  58.12  56.83  46.78  31.30  12.36  24.37  32.34    1
                       70.000  25.50  34.34  22.94  13.86  24.53  28.03  56.35  49.23  46.28  32.38  13.08  22.25  30.76    1
                       70.625  26.23  33.67  24.13  15.17  23.76  27.96  51.91  44.16  45.99  36.33  16.62  23.61  30.82    1
Name: count, Length: 936, dtype: int64

In [15]:
hum_df.isnull().sum()

PARAMETER    0
YEAR         0
LAT          0
LON          0
JAN          0
FEB          0
MAR          0
APR          0
MAY          0
JUN          0
JUL          0
AUG          0
SEP          0
OCT          0
NOV          0
DEC          0
ANN          0
dtype: int64

In [16]:
hum_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  936 non-null    object
 1   YEAR       936 non-null    int64
 2   LAT        936 non-null    float64
 3   LON        936 non-null    float64
 4   JAN        936 non-null    float64
 5   FEB        936 non-null    float64
 6   MAR        936 non-null    float64
 7   APR        936 non-null    float64
 8   MAY        936 non-null    float64
 9   JUN        936 non-null    float64
 10  JUL        936 non-null    float64
 11  AUG        936 non-null    float64
 12  SEP        936 non-null    float64
 13  OCT        936 non-null    float64
 14  NOV        936 non-null    float64
 15  DEC        936 non-null    float64
 16  ANN        936 non-null    float64
dtypes: float64(15), int64(1), object(1)
memory usage: 124.4+ KB

In [17]:
rain_df

,PARAMETER,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,PRECTOTCORR_SUM,2000,28.0,65.625,2.67,1.11,0.06,11.49,1.98,0.33,0.00,9.86,0.00,0.00,10.34,4.45,42.29
1,PRECTOTCORR_SUM,2000,28.0,66.250,1.66,0.77,0.00,4.70,0.63,0.10,0.00,12.97,0.00,0.00,5.61,4.62,31.06
2,PRECTOTCORR_SUM,2000,28.0,66.875,1.14,0.50,0.00,2.65,0.25,0.04,0.01,12.31,0.00,0.00,3.44,4.06,24.40
3,PRECTOTCORR_SUM,2000,28.0,67.500,0.47,0.21,0.00,0.34,0.01,0.00,0.03,7.54,0.00,0.00,0.62,2.33,11.55
4,PRECTOTCORR_SUM,2000,28.0,68.125,0.41,0.18,0.00,0.08,0.00,0.00,0.22,1.89,0.00,0.05,0.02,0.62,3.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
931,PRECTOTCORR_SUM,2025,29.5,68.125,4.14,17.32,1.55,0.00,14.47,9.00,124.16,38.73,9.35,0.02,0.00,9.06,227.80
932,PRECTOTCORR_SUM,2025,29.5,68.750,5.04,16.25,1.22,0.00,8.33,5.02,122.93,35.37,10.05,0.02,0.00,8.87,213.10
933,PRECTOTCORR_SUM,2025,29.5,69.375,2.74,18.23,2.11,0.00,22.57,18.69,119.46,43.68,10.60,1.32,0.00,8.32,247.72
934,PRECTOTCORR_SUM,2025,29.5,70.000,1.57,19.39,2.79,0.00,26.15,36.68,89.93,44.21,16.13,8.27,0.00,6.49,251.61
935,PRECTOTCORR_SUM,2025,29.5,70.625,0.81,16.27,2.39,0.00,17.13,37.85,68.53,36.19,25.23,19.28,0.00,3.86,227.54

In [18]:
rain_df.isnull().sum()

PARAMETER    0
YEAR         0
LAT          0
LON          0
JAN          0
FEB          0
MAR          0
APR          0
MAY          0
JUN          0
JUL          0
AUG          0
SEP          0
OCT          0
NOV          0
DEC          0
ANN          0
dtype: int64

In [19]:
rain_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 936 entries, 0 to 935
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  936 non-null    object
 1   YEAR       936 non-null    int64
 2   LAT        936 non-null    float64
 3   LON        936 non-null    float64
 4   JAN        936 non-null    float64
 5   FEB        936 non-null    float64
 6   MAR        936 non-null    float64
 7   APR        936 non-null    float64
 8   MAY        936 non-null    float64
 9   JUN        936 non-null    float64
 10  JUL        936 non-null    float64
 11  AUG        936 non-null    float64
 12  SEP        936 non-null    float64
 13  OCT        936 non-null    float64
 14  NOV        936 non-null    float64
 15  DEC        936 non-null    float64
 16  ANN        936 non-null    float64
dtypes: float64(15), int64(1), object(1)
memory usage: 124.4+ KB

In [20]:
rain_df.describe()

,YEAR,LAT,LON,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
count,936.00000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000,936.000000
mean,2012.50000,28.750000,68.125000,12.096506,12.941998,21.356229,13.496229,15.998579,15.354412,46.336015,52.261656,12.427201,3.542682,3.970673,6.789252,216.571432
std,7.50401,0.559316,1.614606,23.976097,17.870787,39.460421,26.133095,57.485077,24.044327,90.949605,114.830724,27.196801,16.913971,7.122065,12.933363,256.029304
min,2000.00000,28.000000,65.625000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.470000
25%,2006.00000,28.375000,66.875000,0.470000,1.170000,2.452500,1.305000,1.140000,1.525000,8.197500,3.917500,0.720000,0.000000,0.000000,0.050000,86.195000
50%,2012.50000,28.750000,68.125000,2.240000,4.745000,8.380000,4.840000,3.505000,6.695000,21.425000,17.235000,3.640000,0.205000,0.475000,1.260000,144.715000
75%,2019.00000,29.125000,69.375000,14.920000,17.517500,25.342500,13.710000,9.225000,18.487500,46.915000,44.112500,11.670000,1.680000,5.085000,6.650000,223.067500
max,2025.00000,29.500000,70.625000,218.230000,99.420000,451.690000,222.680000,596.290000,276.970000,831.250000,1032.310000,210.600000,262.180000,44.420000,81.370000,1949.490000